# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: timeoutInMinutes
    value: '60'
  - name: product
    value: slack-help-bot
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: action
    displayName: Action
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environments
    displayName: Environment to run
    type: object
    default:
      - environment: "cftptl"
        storageAccountName: "cftptlintsvc"
        storageAccountRg: "core-infra-intsvc-rg"
        dependsOn: "Precheck"

stages:
  - stage: Precheck
    jobs:
      - job:
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.action }}
              keyvaultName: "infra-vault-nonprod"
              keyvaultSecret: "azure-devops-sp-token"
              serviceConnection: "DCD-CFT-Sandbox"

  - ${{ each parameter in parameters.environments }}:
      - stage: ${{ parameter.environment }}
        displayName: "${{ parameter.environment }}-intsvc"
        dependsOn: ${{ parameter.dependsOn }}
        jobs:
          - job:
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.action }}
                  environment: "ptl"
                  component: infrastructure
                  serviceConnection: "DTS-${{ upper(parameter.environment) }}-INTSVC"
                  terraformInitSubscription: 04d27a32-7a07-48b3-95b8-3c8691e1a263
                  product: ${{ variables.product }}